language: java
install: skip

branches:
  only:
    - master
    - feature/CI

os: linux
dist: trusty
jdk: oraclejdk8
before_install:
  - chmod +x gradlew
  - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
env:
  - COMMIT_MESSAGE=${TRAVIS_COMMIT_MESSAGE}
  - TRAVIS_BRANCH=${TRAVIS_BRANCH}
  - AUTHOR_NAME=${AUTHOR_NAME}
  - TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
  - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
script:
  - echo Branch - ${TRAVIS_BRANCH}
  - echo Commit Message - ${TRAVIS_COMMIT_MESSAGE}
  - echo Author - ${AUTHOR_NAME}
  - echo Is Pull Request - ${TRAVIS_PULL_REQUEST}
  - ./gradlew build --stacktrace
  - ./gradlew run --stacktrace