language: java
install: skip

branches:
  only:
    - master
    - feature/CI

os: linux
dist: trusty
jdk: oraclejdk8
before_install:
  - chmod +x gradlew
  - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
script:
  - echo Branch - ${TRAVIS_BRANCH}
  - echo Commit Message - ${TRAVIS_COMMIT_MESSAGE}
  - echo Author - ${AUTHOR_NAME}
  - echo Is Pull Request - ${TRAVIS_PULL_REQUEST}
  - ./gradlew build --stacktrace
  - ./gradlew run --stacktrace