language: java
install: skip

os: linux
dist: trusty
jdk: oraclejdk8
before_install:
  - chmod +x gradlew
  - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
script:
  - echo ${TRAVIS_COMMIT_MESSAGE}
  - echo $TRAVIS_COMMIT_MESSAGE
  - echo '${TRAVIS_COMMIT_MESSAGE}'
  - echo '$TRAVIS_COMMIT_MESSAGE'
  - |
    curl --location --request POST 'https://discord.com/api/webhooks/853408980066631690/qCPNwy97RdiuV7nx0G--hleg9fA__eFod2yPrJFT9VI99fg4njfU1qNo90iKBZAqtaMk' \
    --header 'Content-Disposition: filename="test.png";' \
    --header 'Content-Type: application/json' \
    --header 'Cookie: __dcfduid=8ed4cc529ee148c0ab36efb3746470c4' \
    --data "{
        \"embeds\": [
            {
                \"color\": 9193502,
                \"description\": \"\`\`\`${TRAVIS_COMMIT_MESSAGE}\`\`\`\",
                \"timestamp\": \"2021-06-12T23:50:06.854Z\",
                \"footer\": {
                    \"text\": \"Update Author: ${AUTHOR_NAME}\"
                }
            }
        ]
    }"
  - |
    curl --location --request POST 'https://discord.com/api/webhooks/853408980066631690/qCPNwy97RdiuV7nx0G--hleg9fA__eFod2yPrJFT9VI99fg4njfU1qNo90iKBZAqtaMk' \
    --header 'Content-Disposition: filename="Techarium.jar";' \
    --header 'Content-Type: multipart/form-data' \
    --header 'Cookie: __dcfduid=8ed4cc529ee148c0ab36efb3746470c4' \
    --form 'file=@"./build/libs/techarium-1.0.jar"'