language: java
install: skip

branches:
  only:
    - master
    - feature/CI

os: linux
dist: trusty
jdk: oraclejdk8
before_install:
  - chmod +x gradlew
  - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
script:
  - ./gradlew build --stacktrace
  - |
    curl --location --request POST "${DISCORD_WEBHOOK_URL}" \
    --header 'Content-Disposition: filename="test.png";' \
    --header 'Content-Type: application/json' \
    --header 'Cookie: __dcfduid=8ed4cc529ee148c0ab36efb3746470c4' \
    --data "{
        \"content\": \"<@&853419684329816074>\",
        \"embeds\": [
            {
                \"color\": 9193502,
                \"description\": \"**Branch:** ${TRAVIS_BRANCH}\n\n**Update Details**:\`\`\`${TRAVIS_COMMIT_MESSAGE}\`\`\`\",
                \"footer\": {
                    \"text\": \"Update Author: ${AUTHOR_NAME}\"
                }
            }
        ]
    }"
  - |
    curl --location --request POST "${DISCORD_WEBHOOK_URL}" \
    --header 'Content-Disposition: filename="Techarium.jar";' \
    --header 'Content-Type: multipart/form-data' \
    --header 'Cookie: __dcfduid=8ed4cc529ee148c0ab36efb3746470c4' \
    --form 'file=@"./build/libs/techarium-1.0.jar"'